name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "YO WELCOME TO MY FUNCTIONAL PROGRAMMING ASSIGNMENT YO, (I'm not as enthusiastic as the ALL-CAPS make me..."
        pr-message: "Don't, it's my work"
